[package]
name = "api"
version = "0.2.0"
edition = "2024"

[dependencies]
axum.workspace = true
base64.workspace = true
chrono.workspace = true
image.workspace = true
infer.workspace = true
jsonwebtoken.workspace = true
kamadak-exif.workspace = true
moka.workspace = true
reqwest.workspace = true
serde.workspace = true
sha2.workspace = true
serde_json.workspace = true
snafu.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
validator.workspace = true
cipher = { path = "../cipher" }
db = { path = "../db" }
memo = { path = "../memo" }
password = { path = "../password" }
storage = { path = "../storage" }
yaas = { path = "../yaas" }
